name = "BatchQuadraticModels"
uuid = "412afcf0-3ec6-4826-be17-8d792afa05a8"
version = "0.1.0"
authors = ["Klamkin, Michael <mklamkin3@gatech.edu>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extensions]
BatchQuadraticModelsCUDAExt = ["CUDA", "KernelAbstractions"]
BatchQuadraticModelsMathOptInterfaceExt = "MathOptInterface"

[compat]
Adapt = "4"
CUDA = "5"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
MathOptInterface = "1.48"
NLPModels = "0.21.10"
SparseArrays = "1.10"
SparseMatricesCOO = "0.2.4"
julia = "1.10"
